apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-postgres-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-postgres-consumer
  template:
    metadata:
      labels:
        app: kafka-postgres-consumer
    spec:
      containers:
        - name: consumer
          image: abdirahman09/smartgridflow-consumer:latest
          imagePullPolicy: IfNotPresent
